pipeline {
  agent any

  stages {

    stage('Build Image') {
      steps {
        sh './build.sh'
      }
    }

    stage('Push Image') {
      steps {
        withCredentials([
          usernamePassword(
            credentialsId: 'dockerhub-creds',
            usernameVariable: 'DOCKER_USER',
            passwordVariable: 'DOCKER_PASS'
          )
        ]) {

          script {

            if (env.BRANCH_NAME == 'dev') {
              sh '''
                echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                docker tag devops-build:latest sudharsanps115/dev:latest
                docker push sudharsanps115/dev:latest
              '''
            }

            if (env.BRANCH_NAME == 'master') {
              sh '''
                echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
                docker tag devops-build:latest sudharsanps115/prod:latest
                docker push sudharsanps115/prod:latest
              '''
            }

          }
        }
      }
    }

    stage('Deploy') {
      steps {
        sh './deploy.sh'
      }
    }
  }
}
