pipeline {
  agent any

  environment {
    IMAGE_NAME = "trend-app"
    DOCKERHUB_REPO = "sudharsanps115/trend-app"
  }

  stages {

    stage('Checkout Code') {
      steps {
         echo "Code already checked out by Jenkins SCM"
      }
    }

    stage('Build Docker Image') {
      steps {
         sh
        '''
        cd TrendStore
        docker build -t $IMAGE_NAME .
        '''
      }
    }

    stage('Push Image to DockerHub') {
      steps {
        sh '''
        cd TrendStore
        docker tag $IMAGE_NAME $DOCKERHUB_REPO:latest
        docker push $DOCKERHUB_REPO:latest
        '''
      }
    }

    stage('Deploy to Kubernetes') {
      steps {
        sh '''
        cd TrendStore
        kubectl apply -f Deployment.yaml
        kubectl apply -f Service.yaml
        '''
      }
    }
  }
}

